FROM ubuntu:latest

RUN apt-get update -y && \
    apt-get install -y python3-pip python3 docker.io

RUN pip install --break-system-packages torch==2.5.1 \
    torchvision \
    seaborn \
    numpy \
    matplotlib \
    tqdm \
    pillow \
    Flask \
    tensorboard \
    transformers \
    protobuf \
    sentencepiece

RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /app
